apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-k3s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kkw855/lakehouse-k3s-gitops.git
    targetRevision: main
    path: apps
    directory:
      recurse: true
      include: "**/*-app.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
