apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lakehouse-k3s-airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4" # Trino 먼저
spec:
  project: default
  sources:
    - repoURL: https://airflow.apache.org
      chart: airflow
      targetRevision: 1.18.0
      helm:
        releaseName: airflow
        valueFiles:
          - $values/apps/airflow/values-airflow.yaml
    - repoURL: https://github.com/kkw855/lakehouse-k3s-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: lakehouse-k3s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
