apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata
  namespace: lakehouse-k3s
spec:
  encryptedData:
    connection: AgC9kyc2IhMJnm14A08hrbEmhxJmYLzVMj9tejPMnO65E0rvu41jXkwzT7TMK7Tn1AP5cWQU4LZ15YVn+epcGDDOCAxDVAd9ultXLSnze/+PI8tJGkNcjKfREE+JUlPapRl6JlY1OqgkyGrJRUeMPBbv7H9ZedMwz6FiMhdKzoEezZLbEHFDxN512AnO++zvqAIMPEvBd5WVd517wmiZfoRLGhaus1ivl7/fSFZYkPL7/iRK/G/Rs0yElZvHvW+5c7JC8ewAUYnOm2ySMkedjEI5IvNjn+xU6uooRWuWNYn4CTuEXtNmHOja8uzHZ/2EDX2vTTsFIGLB1KASJFgtNxakkOQrrxhlFudMH2Yan740F9BRIDiGLRDbmup0p7vVct5vhzxMlzFQPaPa/69I6A6QKyO0OdOt19Nl5UtPcTLHa2LGhyXKfgwB/d4DlyIfmn5n/xtA0eAGE/rlNynl887wbVsnOjtPg6BCLM5MICz590K0qzIPQisccncbQBG6bstj0O92d8qwgYmSLvI5CuD31tflYRXP3gEp+v9WL4lRApB1zrvpdaHVtSS4d/sdmIfNtwHJxqWZFHfkZlPUs7yDR+yMDOtm+RuKlkihEHHpHGPZFh6s4fQLSitBTGBAAC2KJ4CMPvSYlKuKOML/VZRGymVuFfmh1OhffYKCoW0FS3Uanr4eUa6/3nYr5lLVCQ3viCzHhhD0i6WUuThfifyvvR5uue9RBCYjMPKOj+VHGv9nsSxI5TrAe1sJpWRqaO15b3qKPWvABtnkj7F4H22EZXdAqlv5Ke1I2QF3iWXU40QdWHR7jiDwKKQD7xI/6TvG1sOs0y/7oFsKCn9BkeT5jjX2QGWhBva2SUPGqSUnvRrKEYjnDxM=
  template:
    metadata:
      name: airflow-metadata
      namespace: lakehouse-k3s
