apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: lakehouse-k3s
spec:
  encryptedData:
    api-secret-key: AgBdv1AIUwFgHAg6lNkrVBJHsHV9UUWkg9aT6w8RMdp4CoPoSglzDrnCeP44B1Igu5E6Tv3J16tl+IKw2CQp758BvqOBy5xCMXS4fE3vtHFTZ4dqJpmjLvsL7Jx5pmiU4mTKq2Gn802/UQqM21ou9eEyWl9RyzPiogjH5q//oDHvYwTzfNrqWtCfxsAQqWB8KgNGmFOcE43Ze95MUuTdjLDovyXYZxgFsTOwNVjqjRURXuzaLP2JK8WmWqb6oig0h/B/i0di6+K3gYtAo8E9qcz2liHeZTwvGz8iBPWTQsFdu5xbUmmheZpbvBJs4rDPLR9mMN7gOetZMDWJMsA4w2JhrweQuESX3Di4t8OKloyU1S2La6NsTmbg4Uyiv5VmiXHZXDQwS70E6CzwGKJazft2ubslhlAawOEBH7XPzTqCA1swZPumnh723fCvS5h5ZpuokPdgku4wajMdWp8FZcjrHffmpY9j0gvrtV3onJ2Bk/cAY2NwrhzCcn8fwfQJvSqUNKKKGI8hMiLnNke2pWjmHh1tR6AK+ESnz32oe3BmIuoojEg5LF8z9eQaUkx67v8p8CLp9QsqIVdGukbg79wqDe1GSHKLmFMzWsZxWa2eIud4jHWoo9Wi2MaZh4legJxb5fGUj9+Oou0osma9kf8YLZUOIkRA8IANDiaAiAXVN8+os6cO1pC2sJy73O8Mh3NPESIIB8C/bAmNGA96XpSPRij8Qb8Bl33ckUTUYHwADnDwT3TJQ1lOUQTdfopza1bJNIM9BgjZF0xC6sZvZbNc
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: lakehouse-k3s
