apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-jwt-secret
  namespace: lakehouse-k3s
spec:
  encryptedData:
    jwt-secret: AgAW/OtSQsTmmjahPuPzE5Fr2V8g2L8jzHsOYvz1gLyj07yU4Z2CyCRwuy3KGyHDSk1BbJ5sA/N3AC0ZgbNFVEkNRAzgeEKPIZxCGSQdDlbRdMXKbfd+OUcshztMnT9NrbD0s3KmxXolYfW0gFRE/GFqzEZ1nMzukpOKfdKjGEL2L54dz5kDB/tmk8+worhNIls/1Qs2kIvqF8JVca4CBaQ3LgRQnwS3ez5wXOB+8V/3p4fwd5hZnwzU4AccTpWVPAwjZX6KEmRujP0o7bZ+mbDMxR8p0oylQMzsupXSkQ814f8XHkSAcsOngw0SYq6CkejZiP/6ixRNAgXFk0yFkYlSjNWWv4bdVx9RewaCD0/l28J6a03pUX/6h2pAqhlf0liHkbWbhuD+3VJeTiLflYxx5J1tpKqdGJJHjBgiqMJ4tqiowtOLJ5cwtcDICm0aK3AI94BBqw00gmNCd932WRfGnlWncJWdiwpy7cLuKohk48eD7gBM65FLGnHXf34UlpWku7KGGEr1X+M2ZBv8yRlbmGX1dA3flV6iqCFJXdWrhYm8getq4yN0xrFEX3VNJ6LM2DpcOfdxZFeG6GrCO1MhWy4FMJdDc+8X69XHQN8v9UOw7d6p3UVBjuvomo0Al+gH4F6kJJ18EOpKec8aLjCdAxLzMIDfYX5pFQ3L+UAvhLafXk2dr13SXqD0HBbys8yVwmdFXfl+CAI0j+UMD1a0fENy9iQ62gl0Boq8v7Z3dntZuJw44f8AkABUKquKLt/MYsnFUKD7GsQNm0uT+a6n
  template:
    metadata:
      name: airflow-jwt-secret
      namespace: lakehouse-k3s
