---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: lakehouse-k3s
spec:
  encryptedData:
    .dockerconfigjson: AgA6CGkIJMeqbK57T5PKZYNgEO/W/eI8lCjJBhSp3LkMUmRHi1vweACBXMCXQc5pNiR1e8zZsFr1iegR+CHd3fuZSDNeSH16I9TO3GYjvpD2AlSTBbu0FcLlWs1nUNImmB0aHfimL67PmBUx5HuuaNLbMpupM/MlM4lQwRQgSoIy+ZzIHPJKQq9Tmu4k8q/G7Jyg4zZ990UMhk4q9+yriVWGtQyFtP4laNT+xk4BeVSL4YnHn9XjxRrZp5PQISyrgvSI8Z+z5GaBtq8KQ116EZhZQUxQRHmM35IP9nOJMACe3KP4J3MfKX3Vp8zWV1zJgVhC8zJusg3oO0Q6D1SZXIgYY2TMYOsoRpai4FyuniLg1UtIDoHMMMz2Hd66rqI0cHNU6gUKDAmNvjH3eYrFQaVBhUm6cGcB6YjM0fdxVKg9h2xNA+g+fbwG9g0W4y5UnGYC2unVqvHo5Tim5Mib10JzzQaRwwUkuNzwMTpb5y2UJG3eatouLjLxYJpJjJsfXhciq3+mKHbtTdT2yKNTkHyjfJssEBG0F1EEQuw/XZH7gIq9PNhIl491uRVdvwO6LG2rDteGaU7id2kWUOFL+G9fGjzjTYjLHHN4BB9eCyRFFRJovylULIjSN0KbRcu8gKBum5244cs/i4t3VBCBM1nBMDJl6s3fHGIJk+9slcMyXq+aF+AoOUFnmajlJ6GF+jG6T6ZjOUYMkCZw6RX8S+SbpM8daA9wGTKk7WH4cFbgWOZP0SQOfcJuAqxpYN9JraVinP7qkL3OK891CHm8cqvgxOzDobNuUFDNR+QGwu4wTT5Ke1huLBuYpFmIyy7ns8jXPVE5JgCoR3PCKh5nwL7kl7EXoxu0QIec+QFC3jCjvx6c+HQzn5EmEtWXCK1quClxiJKnB5gcrYYrl2+2C7qmbDwD3ST0ZGZg8IE=
  template:
    metadata:
      name: ghcr-secret
      namespace: lakehouse-k3s
    type: kubernetes.io/dockerconfigjson
