---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
  namespace: lakehouse-k3s
spec:
  encryptedData:
    minio-password: AgCTNN0NWDVUCi2zMWv4couVtKJj51stnIv6E/crajooytKR7jaHc4S/nzCygVtrEFmTOpSaT+NUzEzNJ2m8zihFuY7+qIOgbosflPtAXll5lPgoeTEReewUpsXD7UWIJrfcFlb+X9Y+wrFj2hw1BOHA+ZRxy/jQReEFsgpiXpQZUlWFqvHUWYk9btUpkL0+wED20EzrkGXqg5IWkaLV0QcaVqOj1FaZNWc5hOaHLhAb2QeT5rDoLt3cI/RVIk9hB88QPYc6ajfW+5nvDveJwMLgHVIdp02LHRm/tYcE4OPzDV72mt0+6YLv4Utn7hd8tdGpovUQM2+arqvJHTzUq0e763Bzirfa2je+3Ftp3BOukJ26Ka7Ik4BNkT505PrqnW4/V+1bEEUDuEgT85ODxSOYjLpZ+x7l9wWc8LZTdotmJj6m+bTzzVVD8CLQQAV8J7rPC7LEYhEjvzkxIz50btR1YPgaFlmXKRZkICcV4Kb+NNq0brOG8FpalFZlekbpH5FNnVxZLINFt8vAQ/iJkuRNEaulyylnepUd7KnUOhjf8F2kRn3QytB6stugN89E8YA7mCUdbqQd46Qn4Svi34lPGrvhhUuw9um9zEGfsXdxaKr8JD6hQ72zeld4fPpn2UE1mG1rjBQMd7NxvM4kOp8zgMVHc9lzfuayWLWbVak5f6GO7LiDi0GdQod3uOGRLtEo91WQvlWl8Oq57dt8+ZE9WsRF02iiLXETNET/k9Bf
    minio-user: AgCvjgNvFge7a07Hge8I4y2uWe3uqL3UGtxTOSPfKxM6eTzUTnBbyr6qlSGmBL2keYV466Z8ncllVB6gwzbX5NBNFLkfy5+HaC7f2zsQMrjgGbNTjt/Spi6l3uI2fKyYbBOXvwMg0xrvE858laCa9SajY5dYrnH753Pmb7uLrwI7RZ3LJVxlGDSHDT6V232CI7EuN56phpMvc0AUEXmuTKecFesKLT5f9zc28HfJoz/ogH/osnpWS7JNPDasF+Si2aKpvU01lh39cI87Iazlf5d0QStDSVJPrarxgFI7MH43xNHVhCYNCCniQbXKZsjYNK0dyJtxKVy0EU1uqIOz8HIwPPrKbKPzQelMLmDPgW2wQF/FiO6jVHAkqin4jKsE9hCbgBzohZCGS+/XFlyu9J3pU1qTxBxZD+ZqoUjcM+7SsaeQ8cUWS5gKfF3rPObO3cnEerS7FKnInJKEGI9XMP3qAvCOenL63cDK+jalPdVWrvuM672eb1Wl3uV2eS048qTw7e91ya79pX64Q14dIQLEZg9hW+ojVXNR5x0+lYS1/rQ4rl9TzIyyqwRpuS3edGErzZ46PowBYyrCUmwhdf9uXwTqpitWemh+qb5iXQIZ3znFeinzzFMmmIYIBTh6zBfbnJo6jL1akVXKsZpB15W5q94aOopL7f40y+YJmEq8Vn3WuZPwr0fz4vJdSMG/hexr7wdAIf0R7SNJ
  template:
    metadata:
      name: minio-secret
      namespace: lakehouse-k3s
    type: Opaque
