apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-api-secret-key
  namespace: lakehouse-k3s
spec:
  encryptedData:
    api-secret-key: AgCPfDkq/dCwd0gyQCOA60uRiQBu+7GT4RCnpIdp6u312F+LOHTNT//SamgQ7mW1gA668qSKHZoir92cd5k9aVKos/WLv/H6z2y8YVNrlKNe8YM6OvdiHSsnK7A/6Zy8S2tTpv1eSGCRnQc6EaPs2KZ8hKhtwuOwEBB26e8NPerWqg8htgZveF8FMABnDWUEbbL0PNy0kc60s9oWNPX344y+kK/KC5q8EidFAYLVnwTTlNDzwwwbaz279Snd2Nx6ktGQ2IChgTKzaJH3ERiO485dnYGCFmXDKGvoFrI01XG0OySAVHVerIVdZX4Vs4EYLuIQZozqMl348ICIk2v527AjJUKWzvQcdMmu3zMjL9LYlNi2GNgW+tYb1jjER7zz6o3BtNx4ZQP7v49PgsBvJW4RcbeeCHhsVo6/LNqBSTjSUqoqCpUjgEdXFtJJFkoMdVrNPJ75kp6uZpxBT+CJpAIzEOf2uF3CpRrxI8mLaz1O+JQjbZWILw4QJJNwt/w9mfW0PT2NCLtk+Umnuz8Dt08ym7N9lQGldoWo9paTsWShYq1PWyYjcldJBtIP33ADiH5YrRsLoL9WVbTmC6HNrVoPNJhx68QcSZkHwRxpujEccr/tHPUszGUjyl6L2db3IAhuSz6U9Af22hGGu4B/p/PIUI+w5WWSA9Tg25esBmbUqWK/afX0Z8F8TU+YGKpSyJE=
  template:
    metadata:
      name: airflow-api-secret-key
      namespace: lakehouse-k3s
