apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-fernet-key
  namespace: lakehouse-k3s
spec:
  encryptedData:
    fernet-key: AgBEefBbfjlSdpLUfa5d2kbB3AKsglCXDR++5Ywm6kB6qqiCULcUPGEL94OY5997u4VrYwNxlTcjq+nTKglh9l9G6UhABIAdgtmQPv3M3tfF3kzrvRPJUNDZe8qvKLciSyTzaxGKaDEdvh0WUCE1o08XFIngH2nFhwD8EeEvrpGrmj8tOIsuk+vdJdnrKDoEE4ic8xS2z7cNFinfrs4jLgd/fuUth26wFmfzvqnVRa180Rm77S7/aG+mTkMw1/xdTzp+QB/LUeXV5ruVoWhhnM6U8Jg5Xn4cBCzX9VFeLKMSvRPyakj8fXlUwmMF/IakHv3+tqZJxiFLeI8r4sL4gzTgLpJ+9OnYwHtwdhgojZoKesrHdUbKTv4piJ+T1HTau+OezMLjHZV4zFRcQufz6QPs3IrqCr8/UonDI/EOSMX1w9I3ytJ97SzrfUmm9Bm2KKo6jQVW8uG0asSG13QtQCLEofCK1F+sOX7OUWVRi77Jzw6ctZANGuiQeNcYlFRuHX3eiJQLdLBTf7JCqDUGlcIA8b9Z0hilzsMOYTlx9Ipu0B4nz6jvdfTolSaXKQ0RiBNIiVu3VBBygNMMVwfXl6cwgcuVey19XMcbN3x9RWwa/6uvhNsxfojZDTStY55oV5EdHI9do6lnnsNGUuvvtGYjifOL362p2uaE7RLo5WAscT8T4DHpIaywW29aTajtRxkzidsxDQ3VP8jJLDKUTuvxmKgvuS0vbFDCGqSkuOPh2t7H5zvKtT/37CTWeg==
  template:
    metadata:
      name: airflow-fernet-key
      namespace: lakehouse-k3s
