apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: airflow-metadata
  namespace: lakehouse-k3s
spec:
  encryptedData:
    connection: AgAnKFl8O343BH4spkQLRnOjoY9ZhLH3buXL9QvnarV7yDi94UbSm3gxt07f6PWlOSqByunCY7mVPQQ6lInmTROZyZ4IFwVUq7ZZXqlz0G/8/4g/+OgL0G7KHF1onQUK7VeL8/9SfGT+aZ+RVFi+x53jpIBN2wejijaYT/Crzt0j7f0CF331DD4gkxNQh8iAY/ZKjaKBOhnOACCTInAjso7sFebfObdynQgHCZC7lL7R4TkhP1urCT5DI6UgXtIC/BMQW3ZXin83A0QPadBdAz7j0z3c+n+XisIH2wGW5A9L5qOMgfy6i4LRazJ4s5pFoG50MklsV92oxLobcNinYJ+k9Oa6OVivNfGgwRxvLFOgx4mWyMKTctIHhPqHyNoWLY/1laDoTLvBGyu8W/XPlyK/mtB4BzmoYcPJqLyBZYF9vrIzYwOzdd+VTSLu/hQZLUVFIbKqth9wNOyYQt9N3xa5PO3kuKTVNPP0O2EsOzVd7NrVhlwRGadt7F+pyHALf3fqqFbwJBMlUbIgK7u02nT9OSl6v4J84/SEaBDRInUVu0/ocFMHF0aXdF3UZ54bHMvQJzoSa543CCWCUl0KoNIImqtlAAMvoyhWzhJXmk4p+b9rREj80qwNSbooNdcv92kgOoh6XCZr8VyA2aPTg6M55i4TPe3j4A4FY8yHP6WmEWicHjQYha936zbdl28zTodwKMeatHCC1zTrZxH5IXxHporQyBLFkx1U2oVpW9DyaDTClwMaHNW4l9dTcDlolEFn/qg5yz4MoXU0TxIqc9dZU5M=
  template:
    metadata:
      name: airflow-metadata
      namespace: lakehouse-k3s
