---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: lakehouse-k3s
spec:
  encryptedData:
    postgres-password: AgCONIRQ+HxIHZO7JXUTL988sv69DjJq9nNxPIRbgwbX8rFT/2HjJmEpMG2EDRma2M+rK5diLVl/Ez31FMdCltnLfVC7Jp2+iRzog8t/2EQuVcS8AGh7Ts+S5kLE8H4MI0NCyY8uV7EEN35petVSlLhR4rp7bG8WlbQx20/9iOcWIhf1/PYBcsR25l6kjBhnxeRq2qkO1UAPmu4Q5lBqVLwAYyhpfKv0TbRwn4K7DBvD+Ivq9hk3xuYAmzH6235NOd8+xJihYSNMNAGCFwTKrlXe18jtLzIblrtrAG5gMKG7JCaVUXsV9ngQz0bzA/DABrMRi6uJzFiXio2NbRML0+H4sqgsN+733tnwMOpRc+HKz71NFFgMcJIlIyxcvqDTknFcYkgNmTYLfuAt/dLyc9Lax/Hj7TskyBosBRurevnvIB0JR8zaLioGIoaGTknqKjtcxeK4R7Ete80ACnEInpu5rxb0tFUXOOIp+W0XhddThS45NPwakwrlKhmsOtWQB3wMxFtA54ZkMjwza4o1FjZzGQ+D9HfrVjpMBGI1WyuBnxro95DHWmGmYb1zhN6jlnn9p8eUkcIhX1g0O2Jr1b/l9lTF18Emz76dk7cu4o9f9qqsEUVhDOwee0zsLP5myBBz3QqWTmQNcjC0i91gQznqHfEGd9SmJpYpRx5sUKMBpFw9vcTFSY0uiCAxiMRbYQHRY33FzAbqY8ujA3k7vD/SHwQ+lmWROGHGbyWn0TPHggKAUBFC5hKUbjiWvR9huSTAsxS5jQvhclTf9amPCnLn
    postgres-user: AgB2Cz4TxuibhAIS3n021vLvsLj6iAwDBMeagqUCqjFg8b95BSdsPOBvNFUFkFWnIfEe39vZLPZF0YPvcJlcsxmjZ1GQanWVHQ0n655qQ9JiXuJjFcJ1gLonTuvQUQDW/np9HNi09s36jYo0hatVYa7M511axI+sACJtsabdmfChd/kBExRSwXzOzV5oumh7RQ36W6WkFBhMeS0E7oPcczU9GK3WQbLv8F9xE6Ku4qtRDsaNKKBi6Kz3qeAP5avmZgEnxdbNOd/B8cT4t0g9HbLmpX8y/swiIU7zMQojSevQT/9kQElf3Qtj5/OZuw71SyqaZ69MSGbjlP+Jvs2C/ribQBoii3lOR0oA6942MHTOLE7j0IJH84OGJwp7PW27PD3PKKuVlfK3aIYgJBa8ZOyOG+zMhErE5p8CxrqWk6xMacwaFrtQYBWMYhamJySiKZaiLg8dVtRG/HIiVgG3/pPtxUIwFjVQk1Oye8pCSjtW/bUFMgtW2byNXmX1ICSGzPkLpNyLLi58wcjdAEGwSBF3DD8vYV3/B5kPZpwVWcq4aVtqHLXr7FMqZ4OHk3af2AD8tHOA4Mg3ToZtFiowUsE0+Vbf236v4aLBRC1YeGLOMc9nCU1q0cHKDJYdFB1VjMLKEjAVAOkW+2pBqcB/ytWfhjdY2/Aoo+hySMzarWaslfjTFTl17Zg78didw+qDUPiA6JRldw==
  template:
    metadata:
      name: postgres-secret
      namespace: lakehouse-k3s
    type: Opaque
